# Import libraries
library(ggplot2)

# Create data frame
data <- data.frame(
  Sample = c("A02", 
             "A06", 
             "A07", 
             "A08", 
             "A09", 
             "A10", 
             "A11", 
             "A12", 
             "A13"), 
  Sex = c("Male", 
          "Male", 
          "Male", 
          "Male", 
          "Male", 
          "Male", 
          "Male", 
          "Male", 
          "Male"),
  Age = c(18, 
          18, 
          18, 
          18, 
          18, 
          20, 
          20, 
          21, 
          21),
  Weight = c(33.15, 
             35.7,
             34.14,
             35.7,
             34.4,
             42.19,
             40.17,
             41.17,
             40.36
             
  ),
  Type = c("WT", 
           "KO", 
           "KO", 
           "KO",
           "KO",
           "KO",
           "KO",
           "KO",
           "KO"),
  Hematocrit = c(0.49, 
                 0.54, 
                 0.51, 
                 0.55,
                 0.51,
                 0.54,
                 0.53,
                 0.5,
                 0.51),
  Hemoglobine = c(149,
                  180,
                  175,
                  171,
                  155,
                  171,
                  177,
                  155,
                  165),
  Erythrocytes = c(10.8,
                   12.8,
                   12.4,
                   12.1,
                   11.0,
                   11.6,
                   12.2,
                   10.7,
                   11.5),
  VGM = c(45,
          42,
          41,
          45,
          46,
          47,
          43,
          47,
          44),
  CGMH = c(304,
           333,
           343,
           311,
           304,
           317,
           334,
           310,
           324),
  TotalSolids = c(68,
                  76,
                  74,
                  74,
                  66,
                  76,
                  70,
                  70,
                  72),
  Fibrinogen = c(2,
                 2,
                 2,
                 2,
                 2,
                 2,
                 2,
                 2,
                 2),
  Leukocytes = c(3.3,
                 1,
                 4.6,
                 5.2,
                 2.5,
                 4.9,
                 4,
                 2.6,
                 2),
  Neutrophils = c(0.29,
                  0.19,
                  0.69,
                  1.98,
                  1.67,
                  1.47,
                  1.32,
                  0.99,
                  1.04),
  Lymphocytes = c(2.97,
                  0.81,
                  3.91,
                  3.17,
                  0.83,
                  3.43,
                  2.68,
                  1.61,
                  0.96),
  Monocytes = c(0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0),
  Eosinophils = c(0.04,
                  0,
                  0,
                  0.05,
                  0,
                  0,
                  0,
                  0,
                  0),
  Basophils = c(0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0)
)
